version: "3.0"
services:
  app:
    image: python_3.8.1
    container_name: python_3.8.1
    build:
      context: ./containers/python
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 222:222
    volumes:
      # VSCode の拡張などの情報は docker 外に保持する
      - ./volumes/vscode-server:/root/.vscode-server
      # 開発用ディレクトリ
      - ./volumes/opt:/home/lab/opt

      # 各種設定を container へコピー
      - ./conf/.bash_profile:/root/.bash_profile
      - ./conf/gitconfig:/root/.gitconfig:ro

    # INFO: /user/sbin/sshd -D について
    #   container 起動時に sshd がフォアグラウンドで実行され、ssh ログインできるようになる
    command: bash -c "
        echo \"export PASSWORD=${PASSWORD}\" >> ~/.bashrc
        && . ~/.bash_profile
        && /usr/sbin/sshd -D
      "
