version: "3.0"
services:
  app:
    image: python_3.8.1
    container_name: python_3.8.1
    build:
      context: ./containers/python
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 222:222
    volumes:
      # VSCode の拡張などの情報は docker 外に保持する
      - ./volumes/vscode-server:/root/.vscode-server
      # 開発用ディレクトリ
      - ./volumes/opt:/home/lab/opt

      # git の設定を container 内へコピー
      - ./conf/gitconfig:/root/.gitconfig:ro
    env_file:
      - ./conf/env_for_container.env
    # container 起動時に sshd がフォアグラウンドで実行されるために入力を受け付けないが、ssh ログインできるようになる
    command: /usr/sbin/sshd -D
